### ISSUE TITLE
Make a container available for easy deployment

### ISSUE THREAD

**Issue by Jogai** [GyulyVGC/sniffnet#69]
A container makes it easy to test and run software. Containers are common practice among self hosters, and this software looks like it would be of interest to them, I think this is a valuable addition.

Maybe take some inspiration from https://github.com/RustScan/RustScan (its also about networks, and built with rust).

**Comment by GyulyVGC** [comment]
I'm already considering to make a container and I plan to publish it in the near future!

**Comment by GyulyVGC** [comment]
I started drafting a Dockerfile and I encountered some problems.
The build of the container goes smoothly, but when I try to run it I get errors of missing dependencies.
[This](https://github.com/GyulyVGC/sniffnet#required-dependencies) are the dependencies needed from Sniffnet, but it seems that more dependencies are needed to run it from the built container.
This is my current Dockerfile:

```
FROM rust as builder
WORKDIR /usr/src/sniffnet
COPY . .
RUN apt-get update && apt-get install -y libpcap-dev libasound2-dev libfontconfig libfontconfig1-dev && cargo install --path .

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y libpcap-dev libasound2-dev libfontconfig libfontconfig1-dev
COPY --from=builder /usr/local/cargo/bin/sniffnet /usr/local/bin/sniffnet
CMD ["sniffnet"]
```

After the run error which specify the missing dependency, I added it and re-built. But when I run again, another missing dependency is pointed out.

How can I know a priori all the required dependency of this process? It took about 20 minutes to compile the container and I cannot wait this time every time just to find out the next missing dependency.

**Comment by GyulyVGC** [comment]
Update: after having included other apparently needed dependencies (`libxcursor1`, `libxrandr2`, `libxi-dev`, `libx11-xcb-dev`) I now get this error: 

```
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:719:9
```

I've already tried to set `export DISPLAY=:0` as suggested from different sources online, but the error doesn't change.
I will investigate a bit more.

**Comment by AmadeusGraves** [comment]
I find some related issues, @GyulyVGC this may be helpful for you.

https://github.com/bevyengine/bevy/discussions/4921

**Comment by abbbi** [comment]
hi,

The current released debian packages are useless for bullseye as they link against the wrong libssl version, i dont know how these are generated, probably built on a newer debian system (#138)

Cargo shipped with debian bullseye is too old aswell, so building fails anyway.

I made with following dockerfile to create at least a sniffnet executable that can be executed. Howewer, as siffnet uses a library using wgpu for its display, it is crucial you have setup everything required to pass through gpus into the docker container. I havent, such sniffnet currently fails:


```
FROM rust as builder
WORKDIR /usr/src/sniffnet
COPY . .
RUN apt-get update && apt-get install -y libpcap-dev libasound2-dev libfontconfig libfontconfig1-dev && cargo install --path .

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y libpcap-dev libasound2-dev libfontconfig libfontconfig1-dev libxcursor1 libxrandr2 libxi6 libx11-xcb1  xauth
COPY --from=builder /usr/local/cargo/bin/sniffnet /usr/local/bin/sniffnet
CMD ["sniffnet"]
```

```
sudo -E docker run --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --group-add video  --privileged -it a6a5e24a9e5c /usr/local/bin/sniffnet

  /---------------------------------------------------------\
 |     _____           _    __    __                  _      |
 |    / ____|         (_)  / _|  / _|                | |     |
 |   | (___    _ __    _  | |_  | |_   _ __     ___  | |_    |
 |    \___ \  | '_ \  | | |  _| |  _| | '_ \   / _ \ | __|   |
 |    ____) | | | | | | | | |   | |   | | | | |  __/ | |_    |
 |   |_____/  |_| |_| |_| |_|   |_|   |_| |_|  \___|  \__|   |
 |                                                           |
 |                   ___________                             |
 |                  /___________\                            |
 |                 | ___________ |                           |
 |                 | |         | |                           |
 |                 | | v1.1.4  | |                           |
 |                 | |_________| |________________________   |
 |                 \_____________/   by Giuliano Bellini  )  |
 |                 / ''''''''''' \                       /   |
 |                / ::::::::::::: \                  =D-'    |
 |               (_________________)                         |
  \_________________________________________________________/
Error: GraphicsCreationFailed(GraphicsAdapterNotFound)
```

**Comment by abbbi** [comment]
I made it work for me on debian bullseyse with this dockerfile .  My system is setup with amd renoir GPU, setup as such its working with "radeontop". Forwarding the required devices files and xauth stuff via docker command. Alternatively you might want to use docker --gpu all option, if that works out for you.

Build:

sudo docker build . -t sniffnet

Run:

sudo -E docker run --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --group-add video --privileged -it sniffnet



```
FROM rust as builder
WORKDIR /usr/src/sniffnet
COPY . .
RUN apt-get update && apt-get install -y libpcap-dev libasound2-dev libfontconfig libfontconfig1-dev && cargo install --path .

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y libpcap-dev libasound2-dev libfontconfig libfontconfig1-dev libxcursor1 libxrandr2 libxi6 libx11-xcb1  xauth libegl1 libgl1-mesa-dri
COPY --from=builder /usr/local/cargo/bin/sniffnet /usr/local/bin/sniffnet
CMD ["sniffnet"]

```

**Comment by GyulyVGC** [comment]
> PS (#138) I dont know how the released .deb package was built (using cargo helpers?) However, the resulting binary linking against the wrong openssl version suggests the debian package was built on a different system than debian bullseyes and additionally, its missing all the required dependencies in debian/control file, which are usually auto generated by the debian packaging scripts. You might want to change the way you build the debian package at all, becasue the build process seems quite broken.

I'm changing the way packages are created and I need some feedbacks.

Now dependencies are included in the control file and also the openssl version problem should be fixed.

[sniffnet_1.2.0_amd64.deb.zip](https://github.com/GyulyVGC/sniffnet/files/11487966/sniffnet_1.2.0_amd64.deb.zip)

@abbbi could you confirm that this DEB package works fine for you?

**Comment by marc-gav** [comment]
Hi guys. I have started attempting this issue again. You can find my draft PR here: https://github.com/GyulyVGC/sniffnet/pull/455/files

Let me know if I have understood this right. We want a Docker image that can allow users to run the app automatically right?

Could you help me out with this error?
```bash
[+] Building 3.2s (6/6) FINISHED                                                                                                                                                                      docker:desktop-linux
 => [build-image internal] load build definition from Dockerfile                                                                                                                                                      0.0s
 => => transferring dockerfile: 142B                                                                                                                                                                                  0.0s
 => [build-image internal] load metadata for docker.io/homebrew/ubuntu22.04:latest                                                                                                                                    3.0s
 => [build-image internal] load .dockerignore                                                                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                                                                       0.0s
 => [build-image 1/3] FROM docker.io/homebrew/ubuntu22.04:latest@sha256:5575416635b5e552cd8faa54cdfe708f9169200246cd10118c450cbf545a6075                                                                              0.0s
 => CACHED [build-image 2/3] RUN brew install sniffnet                                                                                                                                                                0.0s
 => ERROR [build-image 3/3] RUN ["sniffnet"]                                                                                                                                                                          0.2s
------                                                                                                                                                                                                                     
 > [build-image 3/3] RUN ["sniffnet"]:
0.153 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PcapError("tunl0: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Inappropriate ioctl for device")', src/configs/types/config_device.rs:19:43
0.154 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------
failed to solve: process "sniffnet" did not complete successfully: exit code: 1
```

**Comment by GyulyVGC** [comment]
> Hi guys. I have started attempting this issue again. You can find my draft PR here: https://github.com/GyulyVGC/sniffnet/pull/455/files

Thank you!

> Let me know if I have understood this right. We want a Docker image that can allow users to run the app automatically right?

Yes, this would allow to easily run Sniffnet on any kind of system without worrying about dependencies and the running environment in general

> Could you help me out with this error?
> 
> ```shell
> [...]                                                                                                                                                                                                                
>  > [build-image 3/3] RUN ["sniffnet"]:
> 0.153 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PcapError("tunl0: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Inappropriate ioctl for device")', src/configs/types/config_device.rs:19:43
> 0.154 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> [...]
> ```

This is due an error in the opening of the default network device.
I'm not sure which network interface is considered default in that kind of environment, but it seems that something is not properly setup.

If you got this error I suppose you are using v1.2.2.
Try using the main branch, where in case the default device returns an error I just pass a device with an empty name.
Even in this case though, I suspect we can get anything useful from a fake device... but maybe it can be helpful to start debugging deeper.

**Comment by marc-gav** [comment]
I am studying how Docker deals with networks. I'll get back with some solutions and insights

**Comment by marc-gav** [comment]
Some progress... I am building with 

```Dockerfile
FROM rust:bullseye as builder
RUN apt-get upgrade -y && apt-get update
RUN apt-get install -y libpcap-dev libasound2-dev libfontconfig1-dev libgtk-3-dev
RUN apt-get install -y xorg openbox
RUN cargo install sniffnet
RUN apt-get install libx11-dev
RUN addgroup --system sniffnet
RUN adduser --system sniffnet --ingroup sniffnet
RUN ulimit -n 100000
USER sniffnet
CMD ["sniffnet"]
```

I get the following error:
```bash
➜  sniffnet git:(feat-docker-container-deployment) ✗ docker compose run sniffnet

  /---------------------------------------------------------\
 |     _____           _    __    __                  _      |
 |    / ____|         (_)  / _|  / _|                | |     |
 |   | (___    _ __    _  | |_  | |_   _ __     ___  | |_    |
 |    \___ \  | '_ \  | | |  _| |  _| | '_ \   / _ \ | __|   |
 |    ____) | | | | | | | | |   | |   | | | | |  __/ | |_    |
 |   |_____/  |_| |_| |_| |_|   |_|   |_| |_|  \___|  \__|   |
 |                                                           |
 |                   ___________                             |
 |                  /___________\                            |
 |                 | ___________ |                           |
 |                 | |         | |                           |
 |                 | | v1.2.2  | |                           |
 |                 | |_________| |________________________   |
 |                 \_____________/   by Giuliano Bellini  )  |
 |                 / ''''''''''' \                       /   |
 |                / ::::::::::::: \                  =D-'    |
 |               (_________________)                         |
  \_________________________________________________________/
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/mod.rs:757:9:
Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    %         ```

**Comment by GyulyVGC** [comment]
This error is due to the `winit` dependency used by [Iced](https://github.com/iced-rs/iced), the GUI library used for Sniffnet.
In some Wyland environments this seems to happen and a fix that always work was still not found I think.
Maybe try setting an env var `ICED_BACKEND=tiny-skia` which tells the program to use the fallback graphical renderer.

**Comment by marc-gav** [comment]
Okay I see. I'll look for some references of projects that reliable run Iced inside Docker. As an alternative, a web interface like Pi-Hole could be useful

**Comment by domcyrus** [comment]
@GyulyVGC  would it also be possible to run "sniffnet" without GUI/Display support e.g. using a text based ui which runs in the terminal. This might be easier to approach and it would also be more platform independent so that you could run the docker container on Windows or Mac. What do you think about this approach?

**Comment by GyulyVGC** [comment]
@domcyrus this was discussed in #29:

> I am closing this issue as 'not planned'.
> After having taken into consideration different possibilities, I've come to the conclusion that it's better for me to focus exclusively on the GUI, as I feel like the vast majority of users is more interested on the graphical interface.
> Furthermore, I'm working to add new functionalities to the GUI which would require additional time to be re-implemented also for the TUI (and some of them wouldn't even be feasible).

**Comment by domcyrus** [comment]
Ah sorry I see. Do you still want to have a docker image? I can look into that if this ticket is still feasible and nobody else already works on it.

**Comment by GyulyVGC** [comment]
I'm happy to announce that a [Sniffnet Docker image](https://github.com/users/GyulyVGC/packages/container/package/sniffnet) is finally available in the GitHub Container Registry:

```
docker pull ghcr.io/gyulyvgc/sniffnet:latest
```

For more instructions on how to run the image, see the new Wiki page _[Alternative installation methods](https://github.com/GyulyVGC/sniffnet/wiki/Alternative-installation-methods)_.
